import { StyleSheet } from 'react-native'

import type { ThemeColors } from '../../theme'

const createStyles = (c: ThemeColors) =>
  StyleSheet.create({
    ambientGlow: {
      position: 'absolute',
      width: 400,
      height: 300,
      borderRadius: 200,
      top: -80,
      alignSelf: 'center',
      backgroundColor: 'transparent',
      shadowColor: c.primary,
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.2,
      shadowRadius: 90,
    },
    greetingLabel: {
      fontSize: 10,
      letterSpacing: 2.5,
      textTransform: 'uppercase',
      color: c.textFaint,
      fontWeight: '400',
      marginBottom: 2,
    },
    welcomeName: {
      fontSize: 24,
      fontWeight: '900',
      color: c.textPrimary,
    },
    welcomeSub: {
      fontSize: 12,
      color: c.textMuted,
      fontWeight: '300',
      marginTop: 3,
    },
    statsCard: {
      backgroundColor: c.card,
      borderWidth: 1,
      borderColor: c.cardBorder,
      borderRadius: 16,
      padding: 16,
      marginBottom: 12,
    },
    statsCardPressed: {
      backgroundColor: c.cardPressed,
      borderColor: c.primaryBorder,
    },
    statsLabel: {
      fontSize: 10,
      letterSpacing: 2,
      textTransform: 'uppercase',
      color: c.textFaint,
      fontWeight: '600',
      marginBottom: 4,
    },
    statsHint: {
      fontSize: 11,
      color: c.textMuted,
      lineHeight: 16,
      maxWidth: 180,
    },
    statsTotalWrap: {
      alignItems: 'flex-end',
    },
    statsTotal: {
      fontSize: 32,
      fontWeight: '900',
      color: c.primary,
      lineHeight: 34,
    },
    statsUnit: {
      fontSize: 11,
      fontWeight: '600',
      color: c.textMuted,
      marginTop: 2,
    },
    chartTrack: {
      flexDirection: 'row',
      alignItems: 'flex-end',
      direction: 'ltr',
      height: 128,
      width: '100%',
    },
    barSlot: {
      flexGrow: 1,
      flexShrink: 1,
      flexBasis: 0,
      minWidth: 0,
      alignItems: 'center',
      justifyContent: 'flex-end',
    },
    barWell: {
      height: 88,
      width: '100%',
      alignItems: 'center',
      justifyContent: 'flex-end',
      overflow: 'visible',
    },
    barValue: {
      fontSize: 10,
      fontWeight: '700',
      color: c.textSecondary,
      marginBottom: 4,
      minHeight: 13,
    },
    barValueHidden: {
      opacity: 0,
    },
    barColFilled: {
      backgroundColor: c.primarySoft,
    },
    barDayLabelToday: {
      color: c.primary,
    },
    hintCard: {
      backgroundColor: c.primaryMuted,
      borderWidth: 1,
      borderColor: c.primaryBorder,
      borderRadius: 14,
      padding: 12,
      marginBottom: 14,
    },
    hintText: {
      fontSize: 12,
      color: c.textPrimary,
      lineHeight: 18,
    },
    scrollContent: {
      paddingHorizontal: 20,
      paddingTop: 14,
      paddingBottom: 100,
    },
    sectionCard: {
      backgroundColor: c.card,
      borderWidth: 1,
      borderColor: c.cardBorder,
      borderRadius: 16,
      padding: 16,
      marginBottom: 10,
    },
    sectionCardTitle: {
      fontSize: 12,
      fontWeight: '700',
      color: c.inputOnSurfaceVariant,
    },
    sectionCardPeriod: {
      fontSize: 10,
      color: c.textFaint,
      letterSpacing: 1,
    },
    barCol: {
      width: 10,
      borderRadius: 6,
      backgroundColor: c.cardBorder,
    },
    barColActive: {
      backgroundColor: c.primary,
    },
    barDayLabel: {
      fontSize: 9,
      color: c.textDisabled,
      letterSpacing: 0.2,
      marginTop: 8,
      fontWeight: '600',
      width: '100%',
      textAlign: 'center',
    },
    sectionLabel: {
      fontSize: 10,
      letterSpacing: 2.5,
      textTransform: 'uppercase',
      color: c.textFaint,
      fontWeight: '400',
      marginBottom: 10,
      marginTop: 6,
    },
    featureCard: {
      backgroundColor: c.card,
      borderWidth: 1,
      borderColor: c.cardBorder,
      borderRadius: 16,
      padding: 16,
      marginBottom: 10,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 14,
      minHeight: 72,
    },
    featureCardPressed: {
      backgroundColor: c.cardPressed,
      borderColor: c.primaryBorder,
      transform: [{ scale: 0.99 }],
    },
    featureIcon: {
      width: 46,
      height: 46,
      borderRadius: 12,
      backgroundColor: c.primaryMuted,
      borderWidth: 1,
      borderColor: c.primaryBorder,
      alignItems: 'center',
      justifyContent: 'center',
    },
    featureTitle: {
      fontSize: 15,
      fontWeight: '700',
      color: c.textPrimary,
      marginBottom: 3,
    },
    featureSub: {
      fontSize: 11,
      color: c.textMuted,
      fontWeight: '300',
      lineHeight: 16,
    },
    featureArrow: {
      fontSize: 20,
      color: c.textDisabled,
    },
  })

export { createStyles }
