import { StyleSheet } from 'react-native'

import type { ThemeColors } from '../../theme'

const createStyles = (c: ThemeColors) =>
  StyleSheet.create({
    ambientGlow: {
      position: 'absolute',
      width: 380,
      height: 280,
      borderRadius: 190,
      top: -60,
      alignSelf: 'center',
      backgroundColor: 'transparent',
      shadowColor: c.primary,
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.2,
      shadowRadius: 80,
    },
    brandUnify: {
      fontSize: 20,
      fontWeight: '900',
      color: c.textPrimary,
      letterSpacing: 1,
    },
    brandVoice: {
      fontSize: 20,
      fontWeight: '900',
      color: c.primary,
      letterSpacing: 1,
      textShadowColor: c.primaryGlow,
      textShadowRadius: 12,
      textShadowOffset: { width: 0, height: 0 },
    },
    backBtn: {
      width: 36,
      height: 36,
      borderRadius: 10,
      backgroundColor: c.controlBg,
      borderWidth: 1,
      borderColor: c.controlBorder,
      alignItems: 'center',
      justifyContent: 'center',
    },
    screenTitle: {
      fontSize: 20,
      fontWeight: '900',
      color: c.textPrimary,
    },
    screenSub: {
      fontSize: 11,
      color: c.textMuted,
      fontWeight: '300',
      marginTop: 2,
    },

    // Sign display card
    signCard: {
      backgroundColor: c.card,
      borderWidth: 1,
      borderColor: c.cardBorder,
      borderRadius: 20,
      padding: 20,
      alignItems: 'center',
      marginBottom: 12,
    },
    signCardLabel: {
      fontSize: 9,
      letterSpacing: 2.5,
      textTransform: 'uppercase',
      color: c.textFaint,
      fontWeight: '400',
      alignSelf: 'flex-start',
      marginBottom: 16,
    },
    signAvatarWrap: {
      width: 130,
      height: 130,
      borderRadius: 65,
      backgroundColor: c.primaryMuted,
      borderWidth: 1.5,
      borderColor: c.primaryBorder,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: c.primary,
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.25,
      shadowRadius: 20,
      marginBottom: 12,
    },
    signEmoji: {
      fontSize: 56,
    },
    signPlaceholder: {
      fontSize: 11,
      color: c.textDisabled,
      fontWeight: '300',
      textAlign: 'center',
    },
    currentWordBadge: {
      backgroundColor: c.primarySoft,
      borderWidth: 1,
      borderColor: c.primaryBorderStrong,
      borderRadius: 999,
      paddingHorizontal: 14,
      paddingVertical: 5,
    },
    currentWordText: {
      fontSize: 13,
      fontWeight: '700',
      color: c.primary,
      letterSpacing: 0.5,
    },
    wordChip: {
      backgroundColor: c.controlBg,
      borderWidth: 1,
      borderColor: c.controlBorder,
      borderRadius: 999,
      paddingHorizontal: 10,
      paddingVertical: 4,
    },
    wordChipActive: {
      backgroundColor: c.primary,
      borderColor: c.primary,
    },
    wordChipDone: {
      backgroundColor: c.primaryMuted,
      borderColor: c.primaryBorder,
    },
    wordChipText: {
      fontSize: 11,
      color: c.inputPlaceholder,
      fontWeight: '400',
    },
    replayBtn: {
      marginTop: 14,
      backgroundColor: c.controlBg,
      borderWidth: 1,
      borderColor: c.inputOutline,
      borderRadius: 999,
      paddingHorizontal: 18,
      paddingVertical: 8,
    },
    replayBtnText: {
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 1,
      color: c.inputPlaceholder,
    },

    // Spoken text
    spokenCard: {
      backgroundColor: c.card,
      borderWidth: 1,
      borderColor: c.cardBorder,
      borderRadius: 14,
      padding: 14,
      marginBottom: 12,
    },
    spokenLabel: {
      fontSize: 9,
      letterSpacing: 2.5,
      textTransform: 'uppercase',
      color: c.textFaint,
      fontWeight: '400',
    },
    spokenText: {
      fontSize: 14,
      color: c.textPrimary,
      fontWeight: '400',
      lineHeight: 21,
    },
    clearBtn: {
      fontSize: 11,
      color: c.errorClear,
      fontWeight: '700',
    },

    // Mic card
    micCard: {
      backgroundColor: c.card,
      borderWidth: 1,
      borderColor: c.cardBorder,
      borderRadius: 20,
      padding: 22,
      alignItems: 'center',
      marginBottom: 12,
    },
    waveBar: {
      width: 4,
      height: 40,
      borderRadius: 2,
    },
    micBtn: {
      width: 72,
      height: 72,
      borderRadius: 36,
      backgroundColor: c.controlBg,
      borderWidth: 2,
      borderColor: c.textDisabled,
      alignItems: 'center',
      justifyContent: 'center',
    },
    micBtnActive: {
      borderColor: c.primary,
      backgroundColor: c.primaryMuted,
      shadowColor: c.primary,
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.5,
      shadowRadius: 20,
    },
    micBtnRing: {
      position: 'absolute',
      width: 88,
      height: 88,
      borderRadius: 44,
      borderWidth: 1,
      borderColor: c.primaryBorder,
    },
    micLabel: {
      fontSize: 11,
      color: c.textFaint,
      fontWeight: '400',
      marginTop: 12,
      letterSpacing: 0.3,
    },
    langBadge: {
      backgroundColor: c.controlBg,
      borderWidth: 1,
      borderColor: c.controlBorder,
      borderRadius: 999,
      paddingHorizontal: 10,
      paddingVertical: 4,
    },
    langBadgeText: {
      fontSize: 10,
      color: c.inputPlaceholder,
      fontWeight: '400',
    },

    heroWrap: {
      height: 250,
      marginBottom: 14,
      borderRadius: 16,
      overflow: 'hidden',
      backgroundColor: c.card,
      borderWidth: 1,
      borderColor: c.cardBorder,
    },
    errorCard: {
      backgroundColor: c.errorMuted,
      borderLeftWidth: 3,
      borderLeftColor: c.errorBorder,
      borderRadius: 12,
      padding: 14,
      marginBottom: 12,
    },
    errorTitle: {
      fontSize: 14,
      fontWeight: '700',
      color: c.errorText,
      marginBottom: 4,
    },
    errorBody: {
      fontSize: 13,
      color: c.textPrimary,
      lineHeight: 19,
    },
    signsGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      marginBottom: 14,
    },
    signChip: {
      backgroundColor: c.controlBg,
      borderWidth: 1,
      borderColor: c.controlBorder,
      borderRadius: 999,
      paddingHorizontal: 12,
      paddingVertical: 7,
    },
    signChipText: {
      fontSize: 12,
      color: c.textPrimary,
      fontWeight: '600',
    },
    sectionHint: {
      fontSize: 12,
      color: c.textMuted,
      marginBottom: 10,
      lineHeight: 18,
    },
    secondaryBtn: {
      borderWidth: 1,
      borderColor: c.controlBorder,
      borderRadius: 999,
      paddingVertical: 12,
      alignItems: 'center',
      marginBottom: 10,
      backgroundColor: c.controlBg,
    },
    secondaryBtnText: {
      fontSize: 12,
      fontWeight: '700',
      letterSpacing: 1,
      textTransform: 'uppercase',
      color: c.textMuted,
    },
    // Footer button
    primaryBtn: {
      backgroundColor: c.primaryMuted,
      borderWidth: 1,
      borderColor: c.primaryBorderStrong,
      borderRadius: 999,
      paddingVertical: 13,
      alignItems: 'center',
      shadowColor: c.primary,
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.2,
      shadowRadius: 12,
    },
    primaryBtnText: {
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 2,
      textTransform: 'uppercase',
      color: c.primary,
    },
  })

export { createStyles }
