ENV['RCT_NEW_ARCH_ENABLED'] = '1'
ENV['VISION_CAMERA_ENABLE_NITRO'] = 'false'
# RN 0.84+ defaults to prebuilt RNCore; that breaks RCT_EXPORT_* macros
# in react-native-firebase when using use_frameworks! :linkage => :static.
ENV['RCT_USE_PREBUILT_RNCORE'] = '0'
ENV['RCT_USE_RN_DEP'] = '0'
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip
require_relative '../node_modules/react-native-permissions/scripts/setup'

platform :ios, min_ios_version_supported
prepare_react_native_project!

use_frameworks! :linkage => :static
$RNFirebaseAsStaticFramework = true

target 'FYP' do
  config = use_native_modules!

  setup_permissions([
    'Camera',
    'Microphone',
    'PhotoLibrary',
  ])

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    # ✅ FIX for non-modular header errors
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
      end
    end
  end
end