import { StyleSheet } from 'react-native'

import type { ThemeColors } from '../../../../theme'

const createStyles = (c: ThemeColors) =>
  StyleSheet.create({
    ambientGlow: {
      position: 'absolute',
      width: 400,
      height: 300,
      borderRadius: 200,
      top: -80,
      alignSelf: 'center',
      backgroundColor: 'transparent',
      shadowColor: c.primary,
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.18,
      shadowRadius: 90,
    },
    backBtn: {
      width: 36,
      height: 36,
      borderRadius: 10,
      backgroundColor: c.controlBg,
      borderWidth: 1,
      borderColor: c.controlBorder,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerTitle: {
      fontSize: 14,
      fontWeight: '700',
      color: c.textPrimary,
      letterSpacing: 0.5,
    },
    headerSave: {
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 1.5,
      textTransform: 'uppercase',
      color: c.primary,
    },
    scroll: {
      paddingHorizontal: 20,
      paddingTop: 24,
      paddingBottom: 110,
    },
    avatarWrap: {
      width: 88,
      height: 88,
      position: 'relative',
      marginBottom: 12,
    },
    avatarCircle: {
      width: 88,
      height: 88,
      borderRadius: 44,
      backgroundColor: c.primaryMuted,
      borderWidth: 2,
      borderColor: c.primaryBorderStrong,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: c.primary,
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.25,
      shadowRadius: 16,
    },
    avatarInitials: {
      fontSize: 28,
      fontWeight: '900',
      color: c.primary,
    },
    avatarEditBtn: {
      position: 'absolute',
      bottom: 0,
      right: 0,
      width: 26,
      height: 26,
      borderRadius: 13,
      backgroundColor: c.primary,
      borderWidth: 2,
      borderColor: c.background,
      alignItems: 'center',
      justifyContent: 'center',
    },
    avatarName: {
      fontSize: 18,
      fontWeight: '900',
      color: c.textPrimary,
      marginBottom: 2,
    },
    avatarEmail: {
      fontSize: 12,
      color: c.textMuted,
      fontWeight: '300',
    },
    sectionLabel: {
      fontSize: 9,
      letterSpacing: 2.5,
      textTransform: 'uppercase',
      color: c.textFaint,
      fontWeight: '400',
      marginBottom: 8,
      marginTop: 20,
    },
    groupCard: {
      backgroundColor: c.card,
      borderWidth: 1,
      borderColor: c.cardBorder,
      borderRadius: 16,
      overflow: 'hidden',
    },
    row: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      padding: 14,
      paddingHorizontal: 16,
    },
    rowBorder: {
      borderBottomWidth: 1,
      borderBottomColor: c.rowBorder,
    },
    rowIcon: {
      width: 34,
      height: 34,
      borderRadius: 10,
      backgroundColor: c.primaryMuted,
      borderWidth: 1,
      borderColor: c.primaryBorder,
      alignItems: 'center',
      justifyContent: 'center',
      flexShrink: 0,
    },
    rowIconDanger: {
      backgroundColor: c.errorMuted,
      borderColor: c.errorBorder,
    },
    rowTitle: {
      fontSize: 13,
      fontWeight: '700',
      color: c.textPrimary,
      marginBottom: 1,
    },
    rowSub: {
      fontSize: 11,
      color: c.textFaint,
      fontWeight: '300',
    },
    rowArrow: {
      fontSize: 20,
      color: c.textDisabled,
    },
    badge: {
      backgroundColor: c.primaryMuted,
      borderWidth: 1,
      borderColor: c.primaryBorder,
      borderRadius: 999,
      paddingHorizontal: 8,
      paddingVertical: 2,
    },
    badgeText: {
      fontSize: 9,
      fontWeight: '700',
      letterSpacing: 1,
      textTransform: 'uppercase',
      color: c.primary,
    },
    bottomNav: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      backgroundColor: c.navBackground,
      borderTopWidth: 1,
      borderTopColor: c.divider,
      paddingTop: 10,
      paddingBottom: 24,
    },
    navItem: {
      flex: 1,
      alignItems: 'center',
      gap: 3,
    },
    navIcon: {
      fontSize: 18,
      color: c.textPrimary,
    },
    navLabel: {
      fontSize: 9,
      letterSpacing: 1,
      textTransform: 'uppercase',
      color: c.textMuted,
      fontWeight: '400',
    },
    navDot: {
      width: 3,
      height: 3,
      borderRadius: 1.5,
      backgroundColor: c.primary,
      marginTop: 1,
    },
    overlay: {
      flex: 1,
      backgroundColor: c.overlayStrong,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 24,
    },
    modalCard: {
      backgroundColor: c.surfaceElevated,
      borderWidth: 1,
      borderColor: c.inputOutline,
      borderRadius: 20,
      padding: 24,
      width: '100%',
    },
    modalTitle: {
      fontSize: 18,
      fontWeight: '900',
      color: c.textPrimary,
      marginBottom: 4,
    },
    modalSub: {
      fontSize: 12,
      color: c.textMuted,
      fontWeight: '300',
      marginBottom: 18,
      lineHeight: 18,
    },
    modalLabel: {
      fontSize: 9,
      letterSpacing: 2,
      textTransform: 'uppercase',
      color: c.primary,
      opacity: 0.8,
      fontWeight: '700',
      marginBottom: 6,
    },
    modalInput: {
      backgroundColor: c.controlBg,
      fontSize: 13,
      height: 48,
    },
    langOption: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 14,
      paddingHorizontal: 14,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: c.inputOutline,
      backgroundColor: c.controlBg,
      marginBottom: 10,
    },
    langOptionSelected: {
      borderColor: c.primaryBorderStrong,
      backgroundColor: c.primaryMuted,
    },
    langOptionText: {
      fontSize: 14,
      fontWeight: '600',
      color: c.textPrimary,
    },
    langCheck: {
      fontSize: 16,
      fontWeight: '700',
      color: c.primary,
    },
    avatarImage: {
      width: 88,
      height: 88,
      borderRadius: 44,
    },
    modalErr: {
      backgroundColor: c.errorMuted,
      borderLeftWidth: 3,
      borderLeftColor: c.errorBorder,
      borderRadius: 8,
      paddingHorizontal: 12,
      paddingVertical: 8,
      marginBottom: 14,
    },
    modalErrText: {
      fontSize: 12,
      color: c.errorText,
    },
    cancelBtn: {
      flex: 1,
      backgroundColor: c.controlBg,
      borderWidth: 1,
      borderColor: c.inputOutline,
      borderRadius: 999,
      paddingVertical: 11,
      alignItems: 'center',
    },
    cancelBtnText: {
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 1.5,
      textTransform: 'uppercase',
      color: c.inputPlaceholder,
    },
    saveBtn: {
      flex: 1,
      backgroundColor: c.primaryMuted,
      borderWidth: 1,
      borderColor: c.primaryBorderStrong,
      borderRadius: 999,
      paddingVertical: 11,
      alignItems: 'center',
      shadowColor: c.primary,
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.2,
      shadowRadius: 10,
    },
    saveBtnText: {
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 1.5,
      textTransform: 'uppercase',
      color: c.primary,
    },
  })

export { createStyles }
