import { StyleSheet } from 'react-native'

import type { ThemeColors } from '../../../../theme'

const createStyles = (c: ThemeColors) =>
  StyleSheet.create({
    root: { flex: 1 },
    scroll: {
      paddingHorizontal: 24,
      paddingTop: 12,
      paddingBottom: 110,
    },
    identity: {
      alignItems: 'center',
      marginBottom: 28,
    },
    avatarWrap: {
      width: 108,
      height: 108,
      position: 'relative',
      marginBottom: 10,
      overflow: 'visible',
    },
    avatarCircle: {
      position: 'absolute',
      top: 6,
      left: 6,
      width: 96,
      height: 96,
      borderRadius: 48,
      backgroundColor: c.clay,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: c.shadow,
      shadowOffset: { width: 0, height: 14 },
      shadowOpacity: 0.22,
      shadowRadius: 20,
      elevation: 3,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.primaryBorder,
    },
    chipRow: {
      flexDirection: 'row',
      gap: 8,
      marginTop: 12,
    },
    chip: {
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 999,
      backgroundColor: c.clay,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.primaryBorder,
    },
    chipText: {
      fontSize: 12,
      fontWeight: '700',
      color: c.primary,
    },
    statStrip: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 18,
      minWidth: 220,
    },
    statCell: {
      flex: 1,
      alignItems: 'center',
    },
    statNum: {
      fontSize: 28,
      fontWeight: '800',
      color: c.textPrimary,
      letterSpacing: -0.8,
    },
    statLabel: {
      fontSize: 11,
      fontWeight: '600',
      color: c.textSecondary,
      marginTop: 2,
    },
    statDivider: {
      width: StyleSheet.hairlineWidth,
      height: 36,
      backgroundColor: c.divider,
    },
    themeSwitch: {
      flexDirection: 'row',
      gap: 10,
      marginBottom: 4,
    },
    themePill: {
      flex: 1,
      minHeight: 48,
      borderRadius: 16,
      backgroundColor: c.clay,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.primaryBorder,
    },
    themePillOn: {
      backgroundColor: c.primary,
      borderColor: c.primary,
    },
    themePillText: {
      fontSize: 14,
      fontWeight: '700',
      color: c.textSecondary,
    },
    avatarInitials: {
      fontSize: 28,
      fontWeight: '800',
      color: c.primary,
    },
    avatarImage: {
      width: 96,
      height: 96,
      borderRadius: 48,
    },
    avatarEditBtn: {
      position: 'absolute',
      bottom: 2,
      end: 2,
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: c.primary,
      alignItems: 'center',
      justifyContent: 'center',
      zIndex: 20,
      elevation: 14,
      borderWidth: 2,
      borderColor: c.background,
    },
    avatarName: {
      fontSize: 24,
      fontWeight: '800',
      color: c.textPrimary,
      letterSpacing: -0.4,
    },
    avatarEmail: {
      fontSize: 13,
      color: c.textSecondary,
      marginTop: 4,
      fontWeight: '500',
    },
    sectionLabel: {
      fontSize: 12,
      fontWeight: '700',
      color: c.textSecondary,
      marginBottom: 8,
      marginTop: 22,
    },
    row: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      paddingVertical: 14,
    },
    rowBorder: {
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: c.divider,
    },
    rowIcon: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: c.clay,
      alignItems: 'center',
      justifyContent: 'center',
      flexShrink: 0,
    },
    rowIconDanger: {
      backgroundColor: c.errorMuted,
    },
    rowTitle: {
      fontSize: 15,
      fontWeight: '700',
      color: c.textPrimary,
      marginBottom: 2,
    },
    rowSub: {
      fontSize: 12,
      color: c.textSecondary,
      fontWeight: '400',
      lineHeight: 17,
    },
    badge: {
      paddingHorizontal: 8,
      paddingVertical: 3,
    },
    badgeText: {
      fontSize: 11,
      fontWeight: '700',
      color: c.primary,
    },
    overlay: {
      flex: 1,
      backgroundColor: c.overlayStrong,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 22,
    },
    modalCard: {
      width: '100%',
      backgroundColor: c.glassStrong,
      borderRadius: 24,
      borderWidth: 1,
      borderColor: c.glassBorder,
      padding: 22,
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: '800',
      color: c.textPrimary,
      marginBottom: 4,
    },
    modalSub: {
      fontSize: 13,
      color: c.textSecondary,
      marginBottom: 18,
      lineHeight: 19,
    },
    modalLabel: {
      fontSize: 11,
      fontWeight: '700',
      color: c.primary,
      marginBottom: 6,
    },
    modalInput: {
      backgroundColor: c.glass,
      fontSize: 14,
      height: 48,
    },
    langOption: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 14,
      paddingHorizontal: 4,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: c.divider,
    },
    langOptionSelected: {},
    langOptionText: {
      fontSize: 15,
      fontWeight: '600',
      color: c.textPrimary,
    },
    langCheck: {
      fontSize: 16,
      fontWeight: '700',
      color: c.primary,
    },
    modalErr: {
      marginBottom: 14,
    },
    modalErrText: {
      fontSize: 13,
      color: c.errorText,
      lineHeight: 18,
    },
    cancelBtn: {
      flex: 1,
      paddingVertical: 13,
      alignItems: 'center',
    },
    cancelBtnText: {
      fontSize: 13,
      fontWeight: '700',
      color: c.textSecondary,
    },
    saveBtn: {
      flex: 1,
      backgroundColor: c.primary,
      borderRadius: 999,
      paddingVertical: 13,
      alignItems: 'center',
    },
    saveBtnText: {
      fontSize: 13,
      fontWeight: '800',
      color: c.textOnPrimary,
    },
  })

export { createStyles }
