import { StyleSheet } from 'react-native'

import type { ThemeColors } from '../../theme'

const createStyles = (c: ThemeColors) =>
  StyleSheet.create({
    ambientGlow: {
      position: 'absolute',
      width: 380,
      height: 280,
      borderRadius: 190,
      top: -60,
      alignSelf: 'center',
      backgroundColor: 'transparent',
      shadowColor: c.primary,
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.2,
      shadowRadius: 80,
    },

    brandUnify: {
      fontSize: 20,
      fontWeight: '900',
      color: c.textPrimary,
      letterSpacing: 1,
    },

    brandVoice: {
      fontSize: 20,
      fontWeight: '900',
      color: c.primary,
      letterSpacing: 1,
      textShadowColor: c.primaryGlow,
      textShadowRadius: 12,
      textShadowOffset: { width: 0, height: 0 },
    },

    backBtn: {
      width: 36,
      height: 36,
      borderRadius: 10,
      backgroundColor: c.controlBg,
      borderWidth: 1,
      borderColor: c.controlBorder,
      alignItems: 'center',
      justifyContent: 'center',
    },

    permissionIconWrap: {
      width: 100,
      height: 100,
      borderRadius: 50,
      backgroundColor: c.primaryMuted,
      borderWidth: 1.5,
      borderColor: c.primaryBorderStrong,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: c.primary,
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.3,
      shadowRadius: 20,
    },
    permissionIconRing: {
      position: 'absolute',
      width: 116,
      height: 116,
      borderRadius: 58,
      borderWidth: 1,
      borderColor: c.primaryRing,
    },
    card: {
      backgroundColor: c.card,
      borderWidth: 1,
      borderColor: c.cardBorder,
      borderRadius: 20,
      padding: 22,
    },
    cardTitle: {
      fontSize: 20,
      fontWeight: '900',
      color: c.textPrimary,
      marginBottom: 6,
    },
    cardSub: {
      fontSize: 12,
      color: c.textMuted,
      fontWeight: '300',
      lineHeight: 18,
      marginBottom: 20,
    },
    permRowIcon: {
      width: 34,
      height: 34,
      borderRadius: 10,
      backgroundColor: c.primaryMuted,
      borderWidth: 1,
      borderColor: c.primaryBorder,
      alignItems: 'center',
      justifyContent: 'center',
      flexShrink: 0,
    },
    permRowText: {
      fontSize: 12,
      color: c.inputOnSurfaceVariant,
      fontWeight: '300',
      flex: 1,
      lineHeight: 17,
    },
    dividerLine: {
      height: 1,
      backgroundColor: c.divider,
      marginVertical: 16,
    },
    primaryBtn: {
      backgroundColor: c.primaryMuted,
      borderWidth: 1,
      borderColor: c.primaryBorderStrong,
      borderRadius: 999,
      paddingVertical: 13,
      alignItems: 'center',
      marginBottom: 10,
      shadowColor: c.primary,
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.2,
      shadowRadius: 12,
    },
    primaryBtnText: {
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 2,
      textTransform: 'uppercase',
      color: c.primary,
    },
    secondaryBtn: {
      borderWidth: 1,
      borderColor: c.controlBorder,
      borderRadius: 999,
      paddingVertical: 13,
      alignItems: 'center',
      backgroundColor: c.card,
    },
    secondaryBtnText: {
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 2,
      textTransform: 'uppercase',
      color: c.textMuted,
    },

    screenTitle: {
      fontSize: 20,
      fontWeight: '900',
      color: c.textPrimary,
    },
    screenSub: {
      fontSize: 11,
      color: c.textMuted,
      fontWeight: '300',
      marginTop: 2,
    },
    flipBtn: {
      minWidth: 44,
      minHeight: 44,
      paddingHorizontal: 10,
      borderRadius: 10,
      backgroundColor: c.controlBg,
      borderWidth: 1,
      borderColor: c.controlBorder,
      alignItems: 'center',
      justifyContent: 'center',
    },
    cameraWrap: {
      marginHorizontal: 12,
      minHeight: 280,
      borderRadius: 24,
      overflow: 'hidden',
      backgroundColor: c.card,
      borderWidth: 1,
      borderColor: c.controlBorder,
      position: 'relative',
      justifyContent: 'center',
      alignItems: 'center',
    },
    cameraPlaceholderText: {
      fontSize: 13,
      color: c.textMuted,
      textAlign: 'center',
      fontWeight: '300',
    },
    corner: {
      position: 'absolute',
      width: 22,
      height: 22,
      borderWidth: 2,
      borderColor: c.primary,
      borderRadius: 3,
    },
    guideBox: {
      position: 'absolute',
      borderRadius: 16,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: 'rgba(236,253,245,0.35)',
    },
    guideCorner: {
      position: 'absolute',
      width: 22,
      height: 22,
      borderColor: '#4ade80',
    },
    guideTL: {
      top: -1,
      left: -1,
      borderTopWidth: 3,
      borderLeftWidth: 3,
      borderTopLeftRadius: 14,
    },
    guideTR: {
      top: -1,
      right: -1,
      borderTopWidth: 3,
      borderRightWidth: 3,
      borderTopRightRadius: 14,
    },
    guideBL: {
      bottom: -1,
      left: -1,
      borderBottomWidth: 3,
      borderLeftWidth: 3,
      borderBottomLeftRadius: 14,
    },
    guideBR: {
      bottom: -1,
      right: -1,
      borderBottomWidth: 3,
      borderRightWidth: 3,
      borderBottomRightRadius: 14,
    },
    guideHint: {
      position: 'absolute',
      left: 14,
      right: 14,
      bottom: 12,
      textAlign: 'center',
      color: 'rgba(236,253,245,0.92)',
      fontSize: 12,
      fontWeight: '700',
      textShadowColor: 'rgba(0,0,0,0.65)',
      textShadowOffset: { width: 0, height: 1 },
      textShadowRadius: 4,
    },
    tiltOverlay: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: 'rgba(8, 12, 10, 0.82)',
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 24,
      zIndex: 8,
    },
    tiltPhone: {
      width: 52,
      height: 88,
      borderRadius: 12,
      borderWidth: 3,
      borderColor: '#4ade80',
      backgroundColor: 'rgba(27, 35, 30, 0.95)',
      alignItems: 'center',
      paddingTop: 10,
      marginBottom: 18,
    },
    tiltPhoneScreen: {
      width: 36,
      height: 52,
      borderRadius: 4,
      backgroundColor: 'rgba(74, 222, 128, 0.28)',
    },
    tiltPhoneBar: {
      marginTop: 8,
      width: 16,
      height: 3,
      borderRadius: 2,
      backgroundColor: 'rgba(236,253,245,0.45)',
    },
    tiltTitle: {
      fontSize: 20,
      fontWeight: '800',
      letterSpacing: -0.3,
      textAlign: 'center',
      marginBottom: 8,
    },
    tiltBody: {
      fontSize: 14,
      lineHeight: 20,
      fontWeight: '500',
      textAlign: 'center',
      color: 'rgba(236,253,245,0.88)',
    },
    recBadge: {
      position: 'absolute',
      top: 12,
      left: 12,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      backgroundColor: c.errorMuted,
      borderWidth: 1,
      borderColor: c.errorBorder,
      borderRadius: 999,
      paddingHorizontal: 10,
      paddingVertical: 4,
    },
    recDot: {
      width: 6,
      height: 6,
      borderRadius: 3,
      backgroundColor: c.errorText,
    },
    recText: {
      fontSize: 9,
      fontWeight: '700',
      letterSpacing: 2,
      color: c.errorText,
    },
    outputCard: {
      marginHorizontal: 20,
      marginTop: 12,
      backgroundColor: c.card,
      borderWidth: 1,
      borderColor: c.cardBorder,
      borderRadius: 14,
      padding: 14,
      minHeight: 64,
    },
    resultHead: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 8,
    },
    outputLabel: {
      fontSize: 9,
      letterSpacing: 2.5,
      textTransform: 'uppercase',
      color: c.textFaint,
      fontWeight: '400',
      marginBottom: 6,
    },
    outputText: {
      fontSize: 22,
      fontWeight: '800',
      color: c.textPrimary,
      lineHeight: 28,
      letterSpacing: -0.3,
    },
    outputPlaceholder: {
      fontSize: 15,
      fontWeight: '600',
      color: c.textPrimary,
      lineHeight: 22,
      opacity: 0.35,
    },
    confTrack: {
      marginTop: 12,
      height: 6,
      borderRadius: 3,
      backgroundColor: c.divider,
      overflow: 'hidden',
    },
    confFill: {
      height: 6,
      borderRadius: 3,
    },
    confCaption: {
      marginTop: 6,
      fontSize: 12,
      fontWeight: '600',
      color: c.textSecondary,
    },
    altBlock: {
      marginTop: 14,
    },
    altLabel: {
      fontSize: 12,
      fontWeight: '700',
      color: c.textSecondary,
      marginBottom: 8,
    },
    altRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    altChip: {
      minHeight: 40,
      paddingHorizontal: 14,
      borderRadius: 999,
      backgroundColor: c.clay,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.primaryBorder,
      justifyContent: 'center',
    },
    altChipText: {
      fontSize: 13,
      fontWeight: '700',
      color: c.primary,
    },
    vocabRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 6,
      marginTop: 10,
    },
    vocabChip: {
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: 999,
      backgroundColor: c.clay,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.primaryBorder,
    },
    vocabChipText: {
      fontSize: 11,
      fontWeight: '600',
      color: c.textSecondary,
    },
    tipCard: {
      marginHorizontal: 24,
      marginBottom: 12,
      paddingVertical: 4,
    },
    tipTitle: {
      fontSize: 14,
      fontWeight: '800',
      color: c.textPrimary,
      marginBottom: 6,
    },
    tipBody: {
      fontSize: 13,
      lineHeight: 19,
      color: c.textPrimary,
    },
    tipBtn: {
      alignSelf: 'flex-start',
      marginTop: 12,
      minHeight: 40,
      paddingHorizontal: 14,
      borderRadius: 999,
      backgroundColor: c.primary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    tipBtnText: {
      fontSize: 13,
      fontWeight: '800',
      color: c.textOnPrimary,
    },
    errorCard: {
      marginHorizontal: 20,
      marginTop: 12,
      backgroundColor: c.errorMuted,
      borderLeftWidth: 3,
      borderLeftColor: c.errorBorder,
      borderRadius: 12,
      padding: 14,
    },
    errorTitle: {
      fontSize: 14,
      fontWeight: '700',
      color: c.errorText,
      marginBottom: 4,
    },
    errorBody: {
      fontSize: 13,
      color: c.textPrimary,
      lineHeight: 19,
    },
    processingOverlay: {
      backgroundColor: 'rgba(0,0,0,0.35)',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 10,
    },
    processingText: {
      color: '#fff',
      fontSize: 13,
      fontWeight: '600',
    },
    micStatus: {
      textAlign: 'center',
      fontSize: 12,
      color: c.textFaint,
      fontWeight: '500',
      marginBottom: 4,
    },
    recordBtn: {
      width: 72,
      height: 72,
      borderRadius: 36,
      backgroundColor: c.divider,
      borderWidth: 2,
      borderColor: c.textDisabled,
      alignItems: 'center',
      justifyContent: 'center',
    },
    recordBtnActive: {
      borderColor: c.errorText,
      backgroundColor: c.errorMuted,
      shadowColor: c.errorText,
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.4,
      shadowRadius: 14,
    },
    recordInner: {
      width: 24,
      height: 24,
      borderRadius: 12,
      backgroundColor: c.recordIdle,
    },
    recordInnerActive: {
      width: 18,
      height: 18,
      borderRadius: 4,
      backgroundColor: c.errorText,
    },
    textAction: {
      minHeight: 44,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 4,
    },
    textActionLabel: {
      fontSize: 15,
      fontWeight: '700',
      color: c.primary,
    },
  })

export { createStyles }
